baseURL = "https://cameraman-mule-17738.netlify.com/"
languageCode = "en-us"
title = "| orrymr's site |"
theme = "ananke"
sectionPagesMenu = "main"
disqusShortname = "orrymr"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"

[taxonomies]
   tag = "tags"
